### ISSUE TITLE
Problem to run the application

### ISSUE THREAD

**Issue by kmchen** [lestoni/rochambeau#1]
Hi @lestoni ,

Unfortunately i was not able to run it nor building the docker image. Please see screenshots below.

<img width="1157" alt="Screen Shot 2022-02-15 at 5 13 31 PM" src="https://user-images.githubusercontent.com/697297/154105186-a789c345-0981-474b-a72f-cc5f2c7af03c.png">

<img width="988" alt="Screen Shot 2022-02-15 at 5 13 21 PM" src="https://user-images.githubusercontent.com/697297/154105209-3c866c17-a53f-4e26-bb6d-e4f08554a0f2.png">

**Comment by kmchen** [comment]
Hi @lestoni ,
I'm getting a different problem now. CLI works well but the application doesn't seem to work on port 8000. 

> $ yarn build:clean
> $  yarn build
> $ yarn start
> $ less .env
PORT=8000
LOG_LEVEL='info'
NODE_ENV='development'
POUCHDB_URL='rochambeau-db'
POUCHDB_URL_TEST='rochambeau-db-test'
ROCHAMBEAU_ACCESS_TOKEN='2717ca74-e8c0-4937-8aa4-1fc40d1b45b0'


<img width="684" alt="Screen Shot 2022-02-17 at 3 43 03 PM" src="https://user-images.githubusercontent.com/697297/154505087-2d2caf1f-e5cf-4054-88b2-24756e338f83.png">

**Comment by lestoni** [comment]
Hi @kmchen That is expected response when you access root endpoint, the API is versioned

Please access API Spec docs via `/docs` on which endpoints to access (More info in readme) :)

Best,

**Comment by kmchen** [comment]
Hi @lestoni ,

Sorry, i did not realize it's a backend service. I thought it has a frontend application.
